device-management-toolkit/docs

- docs/APIs/MPSmethods/setamtfeatures.md
> docs(amt): update format for note

- docs/APIs/indexMPS.md
> docs(api): update note format

- docs/APIs/RPSmethods/ciraconfig.md
- docs/APIs/RPSmethods/domains.md
- docs/APIs/RPSmethods/profiles.md
Update endpoints and provide example method/apikey for all ciraconfig apis.  Based on feedback from [MPS Issue #33](https://github.com/open-amt-cloud-toolkit/mps/issues/33).
> fix endpoints for ciraconfig RPS APIs

- docs/APIs/MPSmethods/version.md
- mkdocs.yml
> docs(format): note formatting

- docs/Microservices/RPC/troubleshootingRPC.md
Adding a couple tips for troubleshooting with RPC
> docs(rpc): add a couple tips for troubleshooting

- docs/Docker/dockerLocal.md
Updating Docker setup to reflect github submodules avoiding having to worry about building each repo, and directory structure.
> docs(docker): refactor documentation to reflect submodules

- docs/Local/installMPS.md
- docs/Local/installRPS.md
- mkdocs.yml
updated to use submodules for repos
> using submodules for local setup

- docs/Docker/dockerLocal.md
- docs/General/buildRPC.md
- docs/General/createProfileACM.md
- docs/General/createProfileCCM.md
- docs/Local/installMPS.md
- docs/Microservices/RPS/networkConfig.md
- docs/Tutorials/allowlist.md
- mkdocs.yml
- Update buildRPC.md with links to new resources
- Add 1.1 network config contextual info
- Swap docker to linux first
- Update allowlist tutorial to 1.1
> docs(general): resource links, network config addtl info

- docs/Tutorials/uitoolkit.md
- Update git clone for 1.1
- Add new success image
> docs(ui-toolkit): update for 1.1 tag

- docs/Microservices/MPS/configuration.md
- docs/Microservices/RPS/configuration.md
Adding cors configuration options, and updating some incorrect keys for MPS and RPS configuration.
> docs(configuration): update for cors

- docs/release-notes.md
Updates to release-notes to describe feature and issue changes for 1.1 release
Trying to keep this higher level than the changelog for each repository
> docs(release-notes): release-notes changes for 1.1 release

- docs/letter.md
- docs/release-notes.md
- mkdocs.yml
> docs: letter from the devs

- docs/assets/javascripts/version-select.js
- docs/assets/stylesheets/version-select.css
- mkdocs.yml
- site/index.html
- site/versions.json
This will add a drop-down on the nav to the left for users to switch between versions of the documentation.
These changes won't be visible locally, only on the hosted version of the site. These changes will need to be applied to v1.0 as well and will be applied after this PR is merged. This PR will also update the docs to default to 1.1 -- so we will want to wait until all docs are ready to go before merging this PR.
> docs: support versioned docs

- docs/assets/javascripts/version-select.js
> fix(docs): version request for drop-down

- docs/assets/javascripts/version-select.js
> fix(docs): setting current version

- docs/assets/javascripts/version-select.js
> fix(docs): version redirect

- docs/assets/javascripts/version-select.js
- docs/assets/stylesheets/version-select.css
- mkdocs.yml
> docs: add version selector to v1

- docs/assets/stylesheets/version-select.css
> docs(style): fix css for dropdown

- docs/APIs/MPSmethods/poweraction.md
- docs/Docker/dockerLocal.md
- docs/Microservices/RPC/troubleshootingRPC.md
docs: 
MPSMethods/poweraction.md
RPC/troubleshootingRPC.md
Docker/dockerlocal.md
Relates to these items in the spreadsheet:
39: Some devs responded to a connection failure by trying to run rpc.exe again, not realizing unprovisioning was required. This fact is not in the documentation. Reco: Add info saying you can’t reprovision without first unprovisioning.
42: It wasn’t obvious what the difference was between Boot to BIOS and Reset to BIOS. Reco: Briefly describe ambiguous actions on the PowerAction page and link to that page from the See Connected Devices page. Expand table to include current states and defs of each action.
I also cleaned up Docker Local so that whoever decides to modify and refine it will have a tidy environment to do so.
> docs: #42 and #39 in release along with changes to Docker Local

- mkdocs.yml
- site/versions.json
> build: bump site version to 1.2

- .github/workflows/mkdocs_build.yml
- docs/General/buildRPC.md
- docs/Microservices/RPC/commandsRPC.md
- mkdocs.yml
- readme.md
- site/versions.json
Commands and info for using Docker with RPC
> docs(docker): add docker information for RPC

- docs/Microservices/RPS/configuration.md
> fix(rps): added rps_delay_timer to rps configuration

- docs/Kubernetes/kubernetes.md
- mkdocs.yml
updated docs to include scaling information in Azure Kubernetes
> docs(scaling): adding kubernetes scaling

- docs/Kubernetes/kubernetes.md
> docs(k8s): fix formatting

- docs/Docker/dockerLocal.md
- docs/Docker/overview.md
Docker/overview.md (broken link)
Docker/DockerLocal.md (typo)
> docs: fixes broken link and small typo

- mkdocs.yml
- site/versions.json
> docs: prep for v1.3

- docs/APIs/indexMPS.md
- docs/APIs/indexRPS.md
- docs/General/manageDevice.md
- Update links to 1.3 Swagger link
- Remove unnecessary MPS table with API refactor
- Fix leftover ip->localhost change in GSG
> docs(api): bump to 1.3, slim MPS api page

- readme.md
> docs: add spacing in readme

- site/index.html
> docs(site): default to v1.3.0

- docs/release-notes.md
> docs(release-notes):  Added RPC 1.2.1 change

- docs/release-notes.md
Added AllowList known issue to 1.3 release notes
> docs(release-notes): Add AllowList known issue

- docs/Docker/dockerLocal.md
- docs/Microservices/RPC/commandsRPC.md
- Add -f instructions
- Update rpc with kong path
- Update docker ps output for 1.3
> docs(rpc): update rpc commands and docker ps

- docs/Microservices/MPS/configuration.md
- docs/Microservices/RPS/configuration.md
- docs/Microservices/overview.md
modified:   docs/Microservices/MPS/configuration.md
modified:   docs/Microservices/RPS/configuration.md
modified:   docs/Microservices/overview.md
I tried to strike a balance between adding a bit about log levels but not getting to detailed about Docker commands.
> docs: adding log level content

- docs/General/buildRPC.md
Updated Build RPC documentation.
updated opening paragraph, Figure 1 explanation and Docker Build section.
> docs(rpc): Clarified RPC Build Steps

- docs/Docker/dockerLocal.md
- docs/General/buildRPC.md
- docs/General/createCIRAConfig.md
- docs/General/createProfileACM.md
- docs/General/createProfileCCM.md
- docs/Tutorials/apiTutorial.md
- mkdocs.yml
Rewrite CCM vs ACM and toolkit vs AMT limitation
Error in API tutorial
Grammar/spelling
> docs(general): reword CCM, small errors

- docs/Docker/dockerCloud.md
- docs/Tutorials/apiTutorial.md
- docs/Tutorials/uitoolkit.md
- Added URL comments for accessing Sample Web UI when hosted in Azure
- Added FQDN comment for setting up CIRA profile when hosted in Azure
- Fixed a minor code issue in REST API Call tutorial page
> docs(tutorial fixes): update dockerCloud

- mkdocs.yml
- site/versions.json
> docs(version): prep for v1.4

- docs/Tutorials/uitoolkit.md
- docs/UIToolkit/Bundles/SerialOverLAN.md
- docs/UIToolkit/Bundles/kvm.md
- docs/UIToolkit/Controls/kvmControl.md
- docs/UIToolkit/Controls/serialOverLANControl.md
- docs/UIToolkit/Webpack-Configuration.md
-Removed api key related details from the webpack configuration document
> docs(webpack): remove api key related sections from ui-toolkit

- docs/Microservices/RPS/securityRPS.md
updates to securityRPS.md file for 1.4 release
> docs(rps security): updates to securityRPS.md

- mkdocs.yml
Added site_url value
Commented out Google Analytics
> docs(mkdocs): updated site_url

- docs/release-notes.md
> docs(release-notes): 1.4 release updates

- docs/Docker/dockerLocal.md
- docs/General/loginToRPS.md
- docs/Microservices/MPS/configuration.md
removed default values for web login and kong secret
> docs(auth): Auth updates

- docs/Docker/dockerLocal.md
- docs/Scaling/Docker Swarm/docker-swarm.md
- docs/Scaling/Kubernetes/kubernetes.md
- mkdocs.yml
Added docker swarm deployment in order to test the scaling on a local system.
> feat(docker): added docker swarm documentation

- References/abbreviations.md
- docs/Tutorials/uitoolkit.md
- docs/UIToolkit/Bundles/SerialOverLAN.md
- docs/UIToolkit/Bundles/kvm.md
- docs/UIToolkit/Controls/kvmControl.md
- docs/UIToolkit/Controls/serialOverLANControl.md
- docs/UIToolkit/Webpack-Configuration.md
- mkdocs.yml
modified:   References/abbreviations.md
modified:   docs/Tutorials/uitoolkit.md
modified:   docs/UIToolkit/Bundles/SerialOverLAN.md
modified:   docs/UIToolkit/Bundles/kvm.md
modified:   docs/UIToolkit/Controls/kvmControl.md
modified:   docs/UIToolkit/Controls/serialOverLANControl.md
modified:   docs/UIToolkit/Webpack-Configuration.md
modified:   docs/UIToolkit/localization.md
> docs: moving UIToolkit

- docs/Kubernetes/deployingk8s-aks.md
> docs(k8s): add SSH key description

- site/index.html
> docs(site): default to v1.4.0

- docs/release-notes.md
> docs(release-notes): fixed formatting

- mkdocs.yml
- Hide 1.3 scaling
- Change names
Looks like this got left off the last scaling PR.
> docs(scaling): hide outdated

- docs/Microservices/MPS/configuration.md
- docs/Microservices/RPS/configuration.md
- docs/Topics/logging.md
- mkdocs.yml
> docks(logging): Logging updates

- docs/Docker/dockerLocal.md
- docs/General/buildRPC.md
- docs/General/loginToRPS.md
- docs/Microservices/overview.md
- docs/Tutorials/uitoolkit.md
- mkdocs.yml
> docs: REST api check

- docs/Scaling/Docker Swarm/docker-swarm.md
modified:   docs/Scaling/Docker Swarm/docker-swarm.md
I ran through the existing instructions. I still think somebody should fix that Windows Powershell instruction step 3.
> docs: corrections to Docker Swarm

- docs/APIs/indexMPS.md
- docs/APIs/indexRPS.md
- docs/Docker/dockerLocal.md
- docs/Kubernetes/deployingk8s-aks.md
- docs/Kubernetes/deployingk8s.md
- docs/Topics/guids.md
- docs/Topics/powerstates.md
- docs/Tutorials/apiTutorial.md
- Expand Local K8s Tutorial
- Prep AKS doc for next walkthrough
- Fix any leftover outdated 1.3 links
I'm pretty much a K8s genius now. Kidding, man I wish.  Please review!  90% of changes are within local K8s.  Some updates were made to AKS for mirrored content.  AKS will get a separate pass post-walkthrough.
> docs(scaling): flesh out local k8s

- docs/Kubernetes/deployingk8s-aks.md
- docs/Kubernetes/deployingk8s.md
- Rework AKS Tutorial following walkthrough
- Add new tips to avoid having to use Azure Portal at all, yay!
- Minor cleanup leftover to local K8s
> docs(scaling): rework aks tutorial

- docs/Docker/dockerLocal.md
- docs/General/createCIRAConfig.md
> docs(GSG): small fixes from russ fb

- mkdocs.yml
> docs: fixed special char or symbol

- mkdocs.yml
Rename MQTT to MQTT Eventing based on Russ/Colin feedback.
> docs(mqtt): rename mqtt topic based on fb

- docs/Docker/dockerLocal.md
- docs/Docker/overview.md
- docs/General/buildRPC.md
- docs/General/createCIRAConfig.md
- docs/General/createProfileACM.md
- docs/General/createProfileCCM.md
- docs/General/loginToRPS.md
- docs/Tutorials/apiTutorial.md
- docs/Tutorials/uitoolkit.md
modified:   docs/Docker/overview.md
modified:   docs/General/loginToRPS.md
> docs: small, subtle text changes to addr DXA3U1 feedback

- mkdocs.yml
> fix(nav): turn on sticky nav

- docs/Docker/dockerLocal.md
- docs/General/buildRPC.md
- docs/General/createCIRAConfig.md
- docs/Microservices/RPC/buildRPC_Manual.md
- docs/Microservices/overview.md
- docs/Topics/mqtt.md
- docs/Tutorials/apiTutorial.md
- mkdocs.yml
.\docs\Docker\dockerLocal.md
.\docs\General\buildRPC.md  
.\docs\General\createCIRAConfig.md
.\docs\Microservices\RPC\buildRPC_Manual.md
.\docs\Microservices\overview.md
.\docs\Topics\mqtt.md
.\docs\Tutorials\apiTutorial.md
.\mkdocs.yml
> docs: subtle wording changes for DXA3

- docs/Topics/mqtt.md
- mkdocs.yml
mkdocs.yml
docs/Topics/mqtt.md
> docs: trying new naming strategy for MQTT

- mkdocs.yml
- site/versions.json
> docs(version): move master to 1.5

- docs/release-notes.md
> docs(1.5 release notes): update to 1.5 release notes

- site/index.html
> docs: default site to v1.5.0

- docker-compose.yml
- docs/Docker/dockerLocal.md
- docs/Microservices/MPS/configuration.md
- docs/Microservices/RPS/configuration.md
related to [AB#2258](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/2258)
- [ x] Leverages formatting as provided by https://squidfunk.github.io/mkdocs-material/reference/abbreviations/ 
added connection strings to db; map docs volume in docker compose
> docs: updated db connection strings

- docs/Docker/dockerLocal.md
- docs/General/createWiFiConfig.md
- docs/Tutorials/uitoolkit.md
- mkdocs.yml
Clean up any missing info/steps from 1.4->1.5
> docs(GSG): leftover 1.5 required docs

- mkdocs.yml
- site/versions.json
> docs: create v2.0 version

- site/versions.json
- #136 was not showing, was missing comma
- mike can also do descending so as our versions go up, they'll be shown first and not buried
> fix(version): missing comma and invert

- mkdocs.yml
> docs: rename menu item for MPS

- docker-compose.yml
- docs/Scaling/Kubernetes/deployingk8s-aks.md
- docs/Scaling/Kubernetes/deployingk8s.md
- docs/Scaling/Kubernetes/service-mesh.md
- docs/Scaling/overview.md
- mkdocs.yml
how to enable service mesh in k8s with KUMA.
should satisfy Intel requirements re: mTLS
> feat(security): add docs for enabling KUMA for mTLS

- docs/Docker/dockerLocal.md
> fix(docker): updated docker environment variables

- docs/Scaling/Kubernetes/deployingk8s-eks.md
- docs/Scaling/overview.md
- mkdocs.yml
closes [AB#3476](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/3476)
adding k8 support for Amazon AWS
> docs(eks): added scaling in eks

- docs/Scaling/Kubernetes/deployingk8s.md
> docs(k8s): fixed registrycredentials name

- mkdocs.yml
- site/index.html
> docs(site): move to 2.0.0

- docs/APIs/indexMPS.md
- docs/APIs/indexRPS.md
> docs(api): updated swagger links to 2.0.0

- .github/workflows/mkdocs_build.yml
- docs/Reference/UIToolkit/localization.md
> ci: rename master to main for jobs

- docs/Deployment/database.md
> fix(database): add missing fields to ciraconfigs and domains

- mkdocs.yml
> fix(site): revert site_dir to 2.0

- docs/Tutorials/Scaling/Kubernetes/deployingk8s-aks.md
- docs/Tutorials/Scaling/Kubernetes/deployingk8s-eks.md
- docs/Tutorials/Scaling/Kubernetes/deployingk8s.md
> fix(scaling): change conn string ssl values

- mkdocs.yml
> docs(site): move repo to 2.1

- docs/release-notes.md
> docs(release-notes): removes announcements for 2.1

- docs/Reference/productionVault.md
- mkdocs.yml
- Modify old v1.0 flow to fit >v2.0 changes
Tried lots of different configurations, wasn't able to get the vault cli cmds to work flawlessly all the way through so I opted for Vault UI. If you have time to help troubleshoot, we can offer vault cli as alternative path.
> docs(vault): update old prod vault guide

- docs/GetStarted/buildRPC.md
- docs/Reference/RPC/buildRPC_Manual.md
- docs/Reference/RPC/commandsRPC.md
modified:   docs/GetStarted/buildRPC.md
modified:   docs/Reference/RPC/buildRPC_Manual.md
modified:   docs/Reference/RPC/commandsRPC.md
Yes, see a separate email as there is a lot to consider.
> docs(rpc-go): transition activated device

- docs/GetStarted/buildRPC.md
modified:   docs/GetStarted/buildRPC.md
RB ran into a few gotchas, which this check-in should fix.
> docs(rpc-go): refining rpc-go commands

- docs/Reference/RPC/commandsRPC.md
- [ X] Leverages formatting as provided by https://squidfunk.github.io/mkdocs-material/reference/abbreviations/ 
- [ X] Have viewed and verified edits in rendered form ensuring proper formatting
> feat(rpc-go): adds mention of -json flag for rpc commands

- docs/Deployment/database.md
- docs/Deployment/overview.md
- docs/Deployment/secrets.md
- mkdocs.yml
modified:   docs/Deployment/database.md
modified:   docs/Deployment/overview.md
modified:   docs/Deployment/secrets.md
This is a mere second pass. I expect a 3rd and 4th. I know there will be pushback and corrections. Not a problem. Welcoming the discussion.
> docs: second pass on deployment

- .github/workflows/mkdocs_build.yml
- Dockerfile
- docs/Deployment/database.md
- docs/GetStarted/buildRPC.md
- docs/GetStarted/createCIRAConfig.md
- docs/GetStarted/createProfileACM.md
- docs/GetStarted/createProfileCCM.md
- docs/GetStarted/loginToUI.md
- docs/GetStarted/manageDevice.md
- docs/GetStarted/prerequisites.md
- docs/GetStarted/setup.md
- docs/Reference/MQTT/viewMqttEvents.md
- docs/Reference/RPC/buildRPC_Manual.md
- docs/Reference/architectureOverview.md
- docs/Reference/createProfileTLSConfig.md
- docs/Reference/guids.md
- docs/Tutorials/Scaling/overview.md
- docs/Tutorials/apiTutorial.md
- docs/Tutorials/createWiFiConfig.md
- docs/Tutorials/uitoolkitReact.md
- docs/index.md
- mkdocs.yml
Figure captions and a few odds and ends.
modified:   docs/Deployment/database.md
modified:   docs/GetStarted/buildRPC.md
modified:   docs/GetStarted/createCIRAConfig.md
modified:   docs/GetStarted/createProfileCCM.md
modified:   docs/GetStarted/loginToUI.md
modified:   docs/GetStarted/prerequisites.md
modified:   docs/Reference/MQTT/viewMqttEvents.md
modified:   docs/Reference/RPC/buildRPC_Manual.md
modified:   docs/Reference/architectureOverview.md
modified:   docs/Reference/createProfileTLSConfig.md
modified:   docs/Reference/guids.md
modified:   docs/Tutorials/Scaling/overview.md
modified:   docs/Tutorials/apiTutorial.md
modified:   docs/Tutorials/createWiFiConfig.md
modified:   docs/Tutorials/uitoolkitReact.md
modified:   docs/index.md
> docs: Figure captions plugin

- docs/Tutorials/Scaling/Kubernetes/deployingk8s.md
Updates from Rick's setup.
2nd set of updates will come with 2.2 to swap to using Dockerhub. I still haven't gotten the db to work successfully and stop Kong from restarting. Whenever that is solved, I'll find a more guided path for tackling db for users.
> docs(scaling): local k8s readability

- docs/Reference/powerstates.md
modified:   docs/Reference/powerstates.md
> docs: redesign of power tables

- docs/Reference/powerstates.md
> docs: add LMS information as part of in-band

- docs/Tutorials/Scaling/Kubernetes/deployingk8s-aks.md
> fix(aks): new azure key gen reqs

- mkdocs.yml
- site/versions.json
> site(version): add v2.2.0 support

- docs/release-notes.md
> fix(release-notes): last minute updates for 2.2 release

- docs/release-notes.md
> docs(release-notes): wsman-messages 2.1 update

- docs/release-notes.md
> fix(release-notes): update wsman-messages formatting

- site/index.html
> docs(site): default to 2.2

- docs/release-notes.md
> fix(release-notes): wsman-messages formatting

- docs/Deployment/upgradeVersion.md
- mkdocs.yml
- Document the upgrade path from Minor version to Minor version
Placeholder for LTS migration since I'm assuming with breaking changes that will be a bigger problem.
> docs(deployment): add version upgrade path

- docs/GetStarted/buildRPC.md
- docs/GetStarted/setup.md
- mkdocs.yml
- Go back to pulling full open-amt repo.
- Fix ui-toolkit verisoning
> docs(GSG): use recursive and pull

- mkdocs.yml
> docs: update oamtct to v2.2.1 to for values.yaml fix

- mkdocs.yml
> docs: update oamtct to version 2.2.2

- .github/commitlint.config.js
- .github/workflows/semantic.yml
> ci(semantic): replace bot with workflow for conventional commit

- docs/APIs/indexMPS.md
- docs/APIs/indexRPS.md
- mkdocs.yml
- site/versions.json
> docs(version): move main to 2.3

- docs/APIs/indexMPS.md
- docs/APIs/indexRPS.md
- docs/GetStarted/buildRPC.md
- docs/Reference/RPC/buildRPC_Manual.md
- docs/Reference/RPC/commandsRPC.md
- docs/Reference/RPC/libraryRPC.md
- mkdocs.yml
- site/versions.json
modified:   docs/GetStarted/buildRPC.md
modified:   docs/Reference/RPC/commandsRPC.md
Untracked files:
docs/Reference/RPC/libraryRPC.md
Support for "librarization"
> docs: updating rpc go for librarization

- mkdocs.yml
- templates/release-notes.md
> docs: release notes template

- docs/GetStarted/buildRPC.md
- docs/GetStarted/createProfileACM.md
- docs/GetStarted/createProfileCCM.md
- docs/GetStarted/loginToUI.md
- docs/GetStarted/manageDevice.md
- docs/GetStarted/prerequisites.md
- docs/Reference/RPC/buildRPC_Manual.md
- docs/Reference/RPC/libraryRPC.md
- docs/assets/stylesheets/videos.css
- docs/release-notes.md
- docs/videos.md
- mkdocs.yml
- Embed videos into Getting Started and Release Notes
- Add new 'Video Walkthrough' page where all are together
- Fix RPC Commands with new changes
- Some reshuffling for video space
> docs: embed new video content

- docs/GetStarted/buildRPC.md
- docs/GetStarted/loginToUI.md
- docs/GetStarted/manageDevice.md
- docs/GetStarted/prerequisites.md
- docs/videos.md
- Fix broken links, anchor tags do NOT like x.md like markdown
> docs(videos): fix all the broken links

- docs/release-notes.md
- mkdocs.yml
- site/index.html
> docs(release-notes): updates for 2.3.0 release

- docs/Tutorials/createWiFiConfig.md
modified:   docs/Tutorials/createWiFiConfig.md
Added warning for lack of cellular support.
> docs: adding warning about cellular support

- docs/Reference/MPS/configuration.md
> docs(Security): add minimum Version for TLS

- mkdocs.yml
> docs(version): patch fix for docker build

- docs/Reference/MPS/configuration.md
Reverts open-amt-cloud-toolkit/docs#223
> revert(Security): add minimum Version for TLS (#223)

- docs/APIs/indexMPS.md
- docs/APIs/indexRPS.md
- mkdocs.yml
- site/versions.json
> docs(version): create 2.4 release site

- docs/release-notes.md
- docs/videos.md
> docs: release notes 2.4

- docs/Tutorials/uitoolkitReact.md
Variable name fix for issue #232
> docs(react): fix clone no element error

- readme.md
> docs(readme): update native python install

- docs/APIs/indexMPS.md
- docs/APIs/indexRPS.md
- mkdocs.yml
- site/versions.json
> docs(version): move site to 2.5

- docs/APIs/indexMPS.md
- docs/APIs/indexRPS.md
- mkdocs.yml
- site/versions.json
> docs(version): move to 2.5 correctly

- docs/GetStarted/setup.md
- docs/Reference/sslpostgresLocal.md
- mkdocs.yml
New reference guide for how to enable SSL for local postgres container
> docs(postgres): add new ref for ssl with postgres

- .github/workflows/mkdocs_build.yml
- docs/overrides/partials/footer.html
- mkdocs.yml
- readme.md
- Upgrade Material for new features, improved CSS
- Required changes for 7.x to 8.x migration
> docs(site): upgrade material from 7.x to 8.x

- site/index.html
> docs(site): default to 2.5

- docs/videos.md
> docs(videos): update version to variable

- docs/GetStarted/createProfileACM.md
- docs/GetStarted/createProfileCCM.md
- docs/GetStarted/prerequisites.md
- docs/GetStarted/setup.md
- Updates based on feedback (tdm-gcc, ARM-based devices)
- Minor improvements of Admonitions (start of longer-term revamp/remove effort)
> docs(GSG): user feedback changes

- docs/APIs/indexMPS.md
- docs/APIs/indexRPS.md
- mkdocs.yml
- site/index.html
- site/versions.json
> docs(version): move to 2.6

- docs/release-notes.md
> docs: 2.6 release notes

- .github/workflows/projectsSync.yaml
> ci: add project sync to docs

- mkdocs.yml
> docs(version): move to 2.6.1

- .github/workflows/azureBoardsSync.yml
> ci: add azure boards sync

- docs/APIs/indexMPS.md
- docs/APIs/indexRPS.md
- mkdocs.yml
- site/index.html
- site/versions.json
> docs(version): upgrade site to Nov release

- docs/Deployment/database.md
- docs/Deployment/upgradeVersion.md
> docs(deployment): Steps for 2.7 DB migration

- docs/Deployment/upgradeVersion.md
- docs/release-notes.md
- docs/videos.md
Walkthrough of how to use psql to add columns to postgres
> docs(database): steps to add col

- docs/Tutorials/Scaling/Kubernetes/deployingk8s-eks.md
- Add new steps for EBS CSI driver
- Add steps to resolve user permissions
- Todo: run through with new instance, only tested upgrading existing from 1.22 ->
> docs(eks): update for k8s 1.24

- docs/APIs/indexMPS.md
- docs/APIs/indexRPS.md
- mkdocs.yml
- site/versions.json
> docs(site): upgrade site to Jan release

- docs/Reference/RPC/libraryRPC.md
> docs(references): RPC error charts

- docs/Reference/middlewareExtensibility.md
- mkdocs.yml
- Docs for new middleware features
- Example implementation for multi-tenancy
> docs(references): 2.8 middleware extensibility

- docs/Deployment/upgradeVersion.md
- docs/videos.md
> docs(deployment): 2.8 upgrade steps

- Dockerfile
- docs/assets/stylesheets/mermaid.css
- mkdocs.yml
> fix(docs): update mermaid support

- docs/APIs/indexRPS.md
- mkdocs.yml
- site/versions.json
> docs(site): upgrade site to Mar release

- docs/release-notes.md
- docs/videos.md
> docs(release-notes): march 2023 update

- docs/Reference/troubleshooting.md
- mkdocs.yml
> docs(troubleshooting): add faq and update

- docs/Deployment/database.md
- docs/Deployment/upgradeVersion.md
- docs/GetStarted/buildRPC.md
- docs/Reference/RPC/buildRPC_Manual.md
- Upgrade 2.8 to 2.9 steps
- No more RPC beta
- New ERD:
> docs(deployment): mar db upgrade steps

- docs/APIs/indexRPS.md
- mkdocs.yml
- site/versions.json
This reverts commit 39b7bde178191d533ff852e492ce07c639a17a02.
> revert(site): upgrade site to Apr release (#277)

- docs/APIs/indexRPS.md
- mkdocs.yml
- site/versions.json
> docs(site): upgrade repo to Apr_fixed

- docs/Reference/RPS/createProfileTLSConfig.md
- docs/Reference/productionVault.md
> fix: update vault url

- docs/Reference/RPC/commandsRPC.md
> docs(rpc): add force flag to maintenance command

- docs/release-notes.md
> docs(release-notes): april release notes

- docs/Reference/productionVault.md
> fix: update production vault document

- docs/index.md
- mkdocs.yml
> fix(index): 0 digit breaks links

- docs/Reference/troubleshooting.md
> docs(reference): make troubleshoot qs linkable

- mkdocs.yml
> feat: add dark mode and cookie consent

- docs/APIs/indexMPS.md
- docs/APIs/indexRPS.md
- mkdocs.yml
- site/versions.json
> docs(site): upgrade repo to May

- docs/Deployment/upgradeVersion.md
Ties to https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit/pull/202
> docs(deployment): db upgrade steps for May

- docs/Tutorials/Scaling/Kubernetes/deployingk8s-eks.md
I've included steps for both 14 + 15.  When AWS no longer defaults to 14, I'll remove those 14 steps.
> docs(tutorials): update eks conn string postgres15

- docs/APIs/indexMPS.md
- docs/APIs/indexRPS.md
- mkdocs.yml
- site/versions.json
> docs(site): move repo to June 23 release

- docs/Reference/EA/ieee8021xconfig.md
See API Changes to POST and PATCH here: https://app.swaggerhub.com/apis-docs/rbheopenamt/rps/2.13.0#/IEEE802.1x/Create8021xConfig
> docs(reference): add mschapv2 to 8021x

- docs/release-notes.md
- docs/videos.md
- mkdocs.yml
> docs: june release notes

- site/index.html
> docs(site): redirect to June 23 Release

- docs/Reference/RPC/commandsRPC.md
> docs(reference): add friendly name to rpc activate command

- docs/overrides/partials/main.html
- mkdocs.yml
- site/versions.json
> docs(site): check version warning

- docs/Reference/RPC/commandsRPC.md
> docs(reference): ccm activate local

- docs/videos.md
- mkdocs.yml
- site/index.html
- site/versions.json
> docs(site): redirect to July release

- docs/Deployment/centralizedConfiguration.md
- docs/Deployment/upgradeVersion.md
- docs/GetStarted/setup.md
- docs/Reference/MQTT/viewMqttEvents.md
- docs/Reference/productionVault.md
- docs/Reference/sslpostgresLocal.md
- docs/Reference/troubleshooting.md
- docs/Tutorials/Scaling/Kubernetes/deployingk8s.md
- docs/Tutorials/Scaling/docker-swarm.md
- readme.md
- Update guides to use docker profiles
- `docker-compose` deaded and aliased as of July, move to `docker compose`
> docs: use docker profiles

- docs/release-notes.md
> docs(release-notes): fix bolding

- docs/Deployment/centralizedConfiguration.md
- docs/Reference/MQTT/viewMqttEvents.md
> docs: remove extra docker step

- mkdocs.yml
- site/versions.json
> docs(site): move repo to Aug 23

- docs/Reference/RPC/commandsRPC.md
> docs(reference): local acm activate

- mkdocs.yml
- site/versions.json
> docs(site): move repo to Sep 23

- docs/Reference/MPS/configuration.md
- docs/Reference/RPS/configuration.md
- docs/Reference/faq.md
- docs/Reference/troubleshooting.md
- mkdocs.yml
> docs(reference): faq and configs update

- .github/workflows/mkdocs_build.yml
checkout@v2 and setup-python@v2 are Node 12 and deprecated
> build: Update actions from node12 to 16

- docs/Reference/productionVault.md
> docs(reference): fix vault image

- docs/Deployment/Database/database.md
- docs/Deployment/Database/nosql.md
- docs/Deployment/Database/schema.md
- docs/Deployment/overview.md
- mkdocs.yml
> docs(deployment): mongodb docker deploy

- docs/Deployment/Database/schema.md
- docs/Deployment/upgradeVersion.md
- mkdocs.yml
> docs(deployment): update db for devicestate

- docs/APIs/indexRPS.md
- docs/videos.md
- mkdocs.yml
- site/index.html
- site/versions.json
> docs(site): redirect to Oct 23 Release

- .github/workflows/mkdocs_build.yml
> build: update mkdocs to 9.4.7

- docs/Deployment/Database/schema.md
- docs/Deployment/upgradeVersion.md
> docs(reference): prov cert expiry db changes

- mkdocs.yml
> docs: oct23 patch version

- docs/GetStarted/buildRPC.md
- docs/GetStarted/createProfileACM.md
- docs/Reference/RPC/buildRPC_Manual.md
- docs/Tutorials/Scaling/Kubernetes/deployingk8s-aks.md
- docs/Tutorials/Scaling/Kubernetes/deployingk8s-eks.md
> fix: broken formatting

- docs/Reference/RPC/commandsRPC.md
> docs(reference): local acm smb network share

- docs/GetStarted/setup.md
> fix: remove special chars from kong secret

- mkdocs.yml
> docs(site): move repo to nov 23

- docs/Reference/RPC/commandsRPC.md
> docs(reference): configure addwifiport

- mkdocs.yml
> docs(site): move repo to dec 23

- docs/Deployment/upgradeVersion.md
> docs(deployment): dec23 db steps

- References/abbreviations.md
- docs/Tutorials/ideRedirection.md
- docs/release-notes.md
- docs/videos.md
> docs(release-notes): update release notes for dec 23

- docs/APIs/indexRPS.md
- mkdocs.yml
- site/index.html
- site/versions.json
> docs(site): redirect to dec 23 release

- mkdocs.yml
> docs(site): move repo to feb 23

- mkdocs.yml
> docs(site): move repo to march release

- docs/Reference/RPC/commandsRPC.md
Docs for https://github.com/open-amt-cloud-toolkit/rpc-go/pull/357
> docs(reference): echo password flag

- docs/Reference/RPC/commandsRPC.md
- docs/Reference/RPC/libraryRPC.md
> docs(reference): configure amtpassword

- docs/Reference/productionVault.md
> fix: typo in production vault deployment doc

- .github/workflows/mkdocs_build.yml
- docs/Reference/RPC/commandsRPC.md
- docs/release-notes.md
- docs/videos.md
- mkdocs.yml
- readme.md
- site/versions.json
> docs(release-notes): apr 24 release

- site/index.html
> docs(site): redirect to apr24 release

- mkdocs.yml
> docs(site): april 24 patch 1

- mkdocs.yml
> docs(site): move repo to may24

- site/index.html
> docs(site): redirect to may 24 release

- docs/Reference/EA/RPCConfiguration/localIEEE8021xConfig.md
- docs/Reference/EA/RPCConfiguration/rpcgoConfiguration.md
> docs: update ieee8021x steps

- mkdocs.yml
> docs(site): move repo to jun24

- site/index.html
> docs(site): redirect to jun 24

- .github/workflows/mkdocs_build.yml
> ci: change how message is provided to commit

- .github/workflows/mkdocs_build.yml
- LICENSE
> ci: fix commit message, add license

- SECURITY
> docs: add security policy

- docs/Reference/troubleshooting.md
> docs(reference): add troubleshooting for amt 11.8.65

- docs/Deployment/centralizedConfiguration.md
- docs/GetStarted/createProfileACM.md
- docs/Reference/Console/GetStarted/activateDevice.md
- docs/Reference/Console/GetStarted/setup.md
- mkdocs.yml
> docs(reference): add activation steps to console guide

- mkdocs.yml
> docs(site): move repo to jul24

- site/index.html
> docs(site): redirect to jul 24

- docs/videos.md
> docs(videos): add bsod use case video

- mkdocs.yml
> docs(site): move repo to aug24

- docs/release-notes.md
- mkdocs.yml
- site/versions.json
> docs(release-notes): aug 24 release notes

- site/index.html
> docs(site): redirect to aug 24 release

- docs/Reference/RPC/commandsRPC.md
> docs(reference): ccm config file

- mkdocs.yml
> docs(site): move repo to nov24

- docs/GetStarted/Enterprise/setup.md
- docs/Reference/Console/overview.md
- docs/release-notes.md
- mkdocs.yml
- site/versions.json
> docs(release-notes): nov 24 release notes

- site/index.html
> docs(site): redirect to nov 24 release

- docs/index.md
- mkdocs.yml
> docs: rename oact to device management toolkit

- mkdocs.yml
> docs(site): move repo to march25

- docs/release-notes.md
- site/index.html
> docs(site): redirect to march 25 release

- docs/GetStarted/Enterprise/setup.md
> fix: typo and add missing config field

- docs/index.md
> docs: minor updates

- docs/Tutorials/ocrTutorial.md
> docs: minor updates to ocr tutorial

- docs/APIs/indexMPS.md
> docs: update mps swagger url

- .github/workflows/mkdocs_build.yml
> ci: fix quote issue
